image: php:latest

stages:
  - Build
  - Test
  - Deploy

cache:
  paths:
    - vendor/
    - node_modules/
    
Building:
  stage: Build
  only:
    refs:
      - master
      - develop
  script:
    - bash docker_install.sh > /dev/null
  artifacts:
    paths:
      - node_modules/
      - vendor/

Testing:
  stage: Test
  allow_failure: true
  only:
    refs:
      - master
      - develop
  script:
#    - bash docker_install.sh > /dev/null
    - php vendor/bin/phpunit --coverage-text --colors=never
    
Code quality:
  stage: Test
  allow_failure: true
  only:
    refs:
      - master
      - develop
  script:
    - echo "Not used in this project"

Deploy develop:
  stage: Deploy
  only:
    refs:
      - master
      - develop
  script:
    - 'which ssh-agent || ( apt-get install -qq openssh-client )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

    - ssh gitlabrunner@178.62.209.61
    - cd /var/www/dev_proncar
    - git checkout --force develop
    - git reset --hard ${CI_COMMIT_SHA:0:8}
    - composer install
    - npm run prod
    - php artisan migrate

Deploy production:
  stage: Deploy
  only:
    refs:
      -  master
  when: manual
  script:
    - echo "Work in progress"


