image: php:latest

stages:
  - Build
  - Test
  - Deploy

cache:
  paths:
    - vendor/
    - node_modules/
    
Building:
  stage: Build
  only:
    refs:
      - master
      - develop
  script:
    - bash docker_install.sh > /dev/null
  artifacts:
    paths:
      - node_modules/
      - vendor/

Testing:
  stage: Test
  allow_failure: true
  only:
    refs:
      - master
      - develop
  script:
#    - bash docker_install.sh > /dev/null
    - php vendor/bin/phpunit --coverage-text --colors=never
    
Code quality:
  stage: Test
  allow_failure: true
  only:
    refs:
      - master
      - develop
  script:
    - echo "Not used in this project"

Deploy develop:
  stage: Deploy
  only:
    refs:
      - master
      - develop
  script:
    - ssh $SERVER_USER@$SERVER_HOST
    - $SERVER_PASS
    - cd /var/www/dev_proncar
    - git checkout --force develop
    - git reset --hard YOUR_SHA_HERE
    - composer install
    - npm run prod
    - php artisan migrate

Deploy production:
  stage: Deploy
  only:
    refs:
      -  master
  when: manual
  script:
    - echo "Work in progress"


