image: php:latest

stages:
  - build
  - test

cache:
  paths:
    - vendor/
    - node_modules/
    
before_script:
    - bash ci/docker_install.sh > /dev/null
    
build:
  stage: build
  only:
    refs:
      - master
      - develop
  script:
    - apt-get update -yqq
    - apt-get install gnupg -yqq
    - curl -sL https://deb.nodesource.com/setup_8.x | bash -
    - apt-get install git nodejs libcurl4-gnutls-dev libicu-dev libmcrypt-dev libvpx-dev libjpeg-dev libpng-dev libxpm-dev zlib1g-dev libfreetype6-dev libxml2-dev libexpat1-dev libbz2-dev libgmp3-dev libldap2-dev unixodbc-dev libpq-dev libsqlite3-dev libaspell-dev libsnmp-dev libpcre3-dev libtidy-dev -yqq
    - docker-php-ext-install mbstring pdo_mysql curl json intl gd xml zip bz2 opcache
    - pecl install xdebug
    - docker-php-ext-enable xdebug
    - curl -sS https://getcomposer.org/installer | php
    - php composer.phar install
#    - npm install
  artifacts:
    paths:
#      - node_modules/
      - vendor/

test:
  stage: test
  only:
    refs:
      - master
      - develop
  script:
     - php vendor/bin/phpunit --coverage-text --colors=never
    # - npm test
    
quality:
  stage: test
  only:
    refs:
      - master
      - develop
  script:
    - php vendor/bin/phpunit --coverage-text --colors=never
